version: '3.7'
services:
  nginx:
    build:
      context: ./nginx
    hostname: "nginx"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - ssl-test-network
    restart: unless-stopped

networks:
  ssl-test-network:
    driver: bridge